# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerCompose:
    runs-on: self-hosted
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      WORDPRESS_DB_USER: ${{ secrets.MYSQL_USER }}
      WORDPRESS_DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      WORDPRESS_DB_NAME: ${{ secrets.WORDPRESS_DB_NAME }}
    steps:
    - run: whoami
    - uses: actions/checkout@v3
    - run: docker-compose up -d
